blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin





urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^book/', include('book.urls', namespace='book')),
    url(r'^.*', include('main.urls')),
]

blog/book/urls.py
from django.conf.urls import url
from book import views
urlpatterns = [
    url(r'^$', views.book, name='book'),
]

blog/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

blog/article/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-pubDateTime', )



class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article.title + '-' + str(self.id)

blog/book/models.py
from django.db import models

# Create your models here.

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models.query_utils import Q

from article.models import Article, Comment
from article.forms import ArticleForm

def article(request):
    '''
    Render the article page
    '''
    articles = Article.objects.all()
    itemArray = []
    
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemArray.append(items)
        context = {'itemArray':itemArray}
    return render(request, 'article/article.html', context)


def articleCreate(request):
    '''
        Create a new article instance
            1. If method is GET, render an empty form
            2 . If method is POST, perform form validation. Display error messages if the form is invalid
            3. Save the form to the model and redirect to the article page
    '''
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        print(ArticleForm())
        return render(request, template, {'articleForm':ArticleForm()})
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')
    # Or try this at the last line: return article(request)


def articleRead(request, articleId):
    '''
    Read an article
        1. Get the "article" instance; redirect to the 404 page if not found
        2. Render the articleRead template with article instance and its
            associated comments
    '''
    articleToRead = get_object_or_404(Article, id=articleId)
    context = {
        'article': articleToRead,
        'comments': Comment.objects.filter(article=articleToRead)
    }
    return render(request, 'article/articleRead.html', context)


def articleUpdate(request, articleId):
    ''' 
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
            bound form with error messages
    '''
    articleToUpdate = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=articleToUpdate)
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    # POST
    articleForm = ArticleForm(request.POST, instance=articleToUpdate)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    articleForm.save()
    messages.success(request, '文章已修改')
    return redirect('article:articleRead', articleId=articleId)



def articleDelete(request, articleId):
    '''
    Delete the article instance:
        1. Render the article page if the method is GET
        2. Get the article to delete; redirect to 404 if not found
    '''
    if request.method == 'GET':
        return article(request)
    # POST
    articleToDelete = get_object_or_404(Article, id=articleId)
    articleToDelete.delete()
    messages.success(request, '文章已刪除')
    return redirect('article:article')


def articleSearch(request):
    '''
        Search for articles:
            1. Get the "searchTerm" from the HTML page
            2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) |
                                      Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm':searchTerm}
    return render(request, 'article/articleSearch.html', context)

blog/book/views.py
from django.shortcuts import render

# Create your views here.
def book(request):
    '''
    Render the book page
    '''
    return render(request, 'book/book.html')

blog/main/views.py
from django.shortcuts import render
import datetime


def main(request):
    '''
    Render the main page
    '''
    now = datetime.datetime.now()
    context = {'like':'Django 很棒', 'now':now}
    return render(request, 'main/main.html', context)

def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

def contact(request):
    '''
    Render the contact page
    '''
    return render(request, 'main/contact.html')

blog/article/templates/article/article.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}


<form class="inline" action="{% url 'article:articleSearch' %}">
<input type="text" name="searchTerm">
<input type="submit" value="查詢">
</form>
<a class="inline" href="{% url 'article:articleCreate' %}">新增文章</a>
<br>
{% for items in itemArray %}
	{% for item in items %}
	 {% if forloop.first %}
	   <h3 class="inline"><a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></h3>
			<form class="inline" method="post" action="{% url 'article:articleDelete' item.id %}">
			{% csrf_token %}
			<input type="submit" value="刪除">
			</form>
			<p>發表時間:{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
			<div class=articleContent>{{ item.content|linebreaks|truncatewords_html:9 }}</div>
			<p>瀏覽次數:{{ item.views }},按讚:{{ item.likes }}</p>
		{% else %}
			<p>
			<span class=comment>{{ item.content }}</span><br>
			<span class=commentTime>{{ item.pubDateTime|date:'m 月 d 日 H:i'}}</span>
			</p>
		{% endif %}
	{% endfor %}
	<hr>
{% endfor %}



{% endblock %}

blog/article/templates/article/articleCreateUpdate.html
{% extends 'main/base.html' %}
{% block heading %}
 {% if article %}
 修改文章
 {% else %}
 新增文章
 {% endif %}
{% endblock %}
{% block content %}
{% if article %}
<form method="post" action="{% url 'article:articleUpdate' article.id %}">
{% else %}
{% endif %}
<form method="post" action="{% url 'article:articleCreate' %}">
{% csrf_token %}
{{ articleForm.as_p }}
<input type="submit" value="送出">
<a class="btn" href="{% url 'article:article' %}">放棄</a>
</form>
{% endblock %}

blog/article/templates/article/articleRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}閱讀文章{% endblock %}
{% block content %}


<h3 class="inline">{{ article.title }}</h3>
<a class="btn inline" href="{% url 'article:articleUpdate' article.id %}">修改</a>
<p>發表時間:{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
<div class=articleContent>{{ article.content|linebreaks }}</div>
<p>讚:{{ article.likes }}</p>
{% for comment in comments %}
<p>
<span class=comment>{{ comment.content }}</span><br>
<span class=commentTime>{{ comment.pubDateTime|date:'m 月 d 日 H:i'}}</span>
</p>
{% endfor %}


{% endblock %}

blog/article/templates/article/articleSearch.html
{% extends 'main/base.html' %}
{% block heading %}查詢{% endblock %}
{% block content %}


<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
 <input type="text" name="searchTerm">
 <input class="btn" type="submit" value="查詢">
</form>
<br><br><hr>
{% if not articles %}
 <p>查無資料</p>
{% else %}
 <table class="table table-striped table-hover">
 <tr><th>標題</th><th>發表時間</th></tr>
 {% for article in articles %}
 <tr>
 <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
 <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
 </tr>
 {% endfor %}
 </table>
{% endif %}


{% endblock %}

blog/book/templates/article/article.html
<!doctype html>
<html>
<head>
<title>BOOK</title>
<meta charset="utf-8">
</head>
<body>
<h1>BOOK!!!</h1>
<br>
<p><a href="{% url 'main:main' %}">回首頁</a></p>
</body>
</html>

blog/book/templates/book/book.html
<!doctype html>
<html>
<head>
<title>BOOK</title>
<meta charset="utf-8">
</head>
<body>
<h1>BOOK!!!</h1>
<br>
<p><a href="{% url 'main:main' %}">回首頁</a></p>
</body>
</html>

blog/main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
<p>歡迎來到我的部落格,您可盡情瀏覽並留言。</p><br>
{% endblock %}

blog/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% block css %}{% endblock %}
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格 -- {% block heading %}{% endblock %}</h2>
{% include 'main/messages.html' %}
{% block content %}{% endblock %}
</body>
</html>

blog/main/templates/main/contact.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>聯絡我們</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>如何聯絡</h1>
<p>E-mail:abc123@gmail.com</p>
<p><a href="{% url 'main:main' %}">回首頁</a></p>
</body>
</html>

blog/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block heading %}首頁{% endblock %}
{% block content %}
<p>{{ like }}</p>
<p><a href="{% url 'book:book' %}">BOOK</a></p>
<p>現在時間:{{ now }}</p>
{% endblock %}

blog/main/templates/main/menu.html
<ul id="menu">
 <li><a href="{% url 'main:main' %}">首頁</a></li>
 <li><a href="{% url 'main:about' %}">關於</a></li>
 <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>

blog/main/templates/main/messages.html
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}